applications:
- api_domain: cron-rc.app.dev.aws.pulseapi.com
  application_name: https://rc.app.dev.aws.pulseapi.com/
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://rc.app.dev.aws.pulseapi.com/
  type: web
